server:
  port: 8084

spring:
  application:
    name: executor-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

chronoflow:
  job-service:
    url: ${JOB_SERVICE_URL:http://localhost:8082}
  executor:
    simulated-duration-ms: 500

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318}/v1/traces

logging:
  level:
    root: INFO
